<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.conetex.runtime.instrument</groupId>
    <artifactId>parent</artifactId>
    <version>0.0.1</version>

    <name>org.conetex.runtime.instrument</name>
    <description>org.conetex.runtime.instrument</description>

    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>18</maven.compiler.source>
        <maven.compiler.target>18</maven.compiler.target>
        <maven.compiler.release>18</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <module>interfaces</module>
        <module>counter</module>
        <module>collection</module>
        <module>metrics-cost</module>
        <module>metrics-cost-unnamed</module>
        <module>agent</module>
        <module>tests</module>
        <module>example</module>
    </modules>

    <url>https://github.com/conetex/org-conetex-runtime-instrument</url>

    <licenses>
        <license>
            <name>Apache License 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
        </license>
    </licenses>

    <scm>
        <url>https://github.com/conetex/org-conetex-runtime-instrument</url>
        <connection>scm:git:https://github.com/conetex/org-conetex-runtime-instrument.git</connection>
        <developerConnection>scm:git:git@github.com/conetex/org-conetex-runtime-instrument.git</developerConnection>
    </scm>

    <developers>
        <developer>
            <id>matthias-franke</id>
            <name>Matthias Franke</name>
        </developer>
    </developers>

    <build>
        <plugins>

            <!-- JAR (needed for publish) -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <!--<goal>jar</goal>-->
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Javadoc (needed for publish) -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals><goal>jar</goal></goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Sign (needed for publish) -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>verify</phase>
                        <goals><goal>sign</goal></goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Publish -->
            <plugin>
                <groupId>org.sonatype.central</groupId>
                <artifactId>central-publishing-maven-plugin</artifactId>
                <version>0.9.0</version>
                <extensions>true</extensions>
                <configuration>
                    <publishingServerId>central</publishingServerId>
                    <excludeArtifacts>

                        <artifact>example</artifact>

                        <artifact>test-parent</artifact>
                        <!-- tests modules -->
                        <artifact>empty</artifact>
                        <artifact>integration</artifact>
                        <artifact>jar</artifact>
                        <artifact>jar-blocked</artifact>
                        <artifact>jar-module</artifact>
                        <!-- tests modules -->

                    </excludeArtifacts>
                </configuration>
            </plugin>

            <!-- JaCoCo java code coverage -->
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.14</version>
                <executions>
                    <!-- start the jacoco agent before tests -->
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>

                    <!-- create HTML-report after tests -->
                    <execution>
                        <id>report</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>


            <!-- DOC -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <version>4.0.0-M13</version>
                <configuration>
                    <siteDirectory>src/site</siteDirectory>
                </configuration>
            </plugin>

            <!-- DOC plantuml -->
            <plugin>
                <groupId>com.github.jeluard</groupId>
                <artifactId>plantuml-maven-plugin</artifactId>
                <version>1.2</version>
                <inherited>false</inherited>

                <dependencies>
                    <dependency>
                        <groupId>net.sourceforge.plantuml</groupId>
                        <artifactId>plantuml</artifactId>
                        <version>1.2025.2</version>
                    </dependency>
                </dependencies>

                <executions>
                    <execution>
                        <id>generate-plantuml</id>

                        <phase>pre-site</phase>

                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>

                <configuration>
                    <sourceFiles>
                        <directory>${project.basedir}/src/site/plantuml</directory>

                        <includes>
                            <include>**/*.puml</include>
                        </includes>
                    </sourceFiles>

                    <outputDirectory>
                        ${project.build.directory}/site/images
                    </outputDirectory>

                    <format>svg</format>
                </configuration>
            </plugin>



        </plugins>
    </build>

    <!--<reporting>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>3.5.0</version>
            </plugin>

        </plugins>
    </reporting>-->

</project>