= interfaces

include::../_navigationForChildren.adoc[]

[#purpose]
== Purpose

The `interfaces` module defines the *shared APIs and contracts* used across all instrumentation modules. +
Its responsibilities include:

* defining common interfaces for counters, cost metrics, and data collectors
* providing stable abstractions for instrumentation components
* ensuring loose coupling between modules

In essence:

____

The `interfaces` module is the shared contract layer that all instrumentation modules depend on.

____

'''

=== Out of Scope (Handled by Other Modules)

* *Implementing counters or cost metrics* +
 Implemented in: xref:../counter/index.adoc#purpose[`counter`], xref:../../../metrics-cost/index.adoc#purpose[`metrics-cost`]

* *Collecting or aggregating measurement data* +
 Implemented in: xref:../collection/index.adoc#purpose[`collection`]

* *Performing bytecode transformation* +
 Implemented in: xref:../metrics-cost/index.adoc#purpose[`metrics-cost`], xref:../../../metrics-cost-unnamed/index.adoc#purpose[`metrics-cost-unnamed`], xref:../counter/index.adoc#purpose[`counter`]

* *Activating the instrumentation system* +
 Implemented in: xref:../agent/index.adoc#purpose[`agent`]

* *Providing example usage* +
 Implemented in: xref:../example/index.adoc#purpose[`example`]