= counter

include::../navigationForChildren.adoc[]

[#purpose]
== Purpose

The `counter` module provides *runtime counters* that can be injected into instrumented code. +
Its responsibilities include:

* defining counter types (e.g., invocation counters)
* implementing the logic for incrementing and tracking counts
* integrating with the instrumentation transformer to inject counter operations

In essence:

____

The `counter` module supplies the logic for counting events and method invocations during runtime.

____

'''

=== Out of Scope (Handled by Other Modules)

* *Collecting and aggregating counter results* +
 Implemented in: xref:../collection/index.adoc#purpose[`collection`]

* *Activating the instrumentation system* +
 Implemented in: xref:../agent/index.adoc#purpose[`agent`]

* *Defining shared instrumentation interfaces* +
 Implemented in: xref:../../../interfaces/index.adoc#purpose[`interfaces`]

* *Injecting cost or timing measurements* +
 Implemented in: xref:../../../metrics-cost/index.adoc#purpose[`metrics-cost`], xref:../../../metrics-cost-unnamed/index.adoc#purpose[`metrics-cost-unnamed`]

* *Providing example usage* +
 Implemented in: xref:../../../example/index.adoc#purpose[`example`]