= metrics-cost

include::../navigationForChildren.adoc[]

[#purpose]
== Purpose

The `metrics-cost` module implements *cost and timing measurement* for instrumented code. +
Its responsibilities include:

* defining cost metrics (e.g., execution time, resource usage)
* injecting measurement logic into bytecode via a transformer
* producing measurement events consumed by the `collection` module

In essence:

____

The `metrics-cost` module provides the logic and bytecode transformation required to measure execution cost at runtime.

____

'''

=== Out of Scope (Handled by Other Modules)

* *Collecting or aggregating cost data* +
 Implemented in: xref:../collection/index.adoc#purpose[`collection`]

* *Providing counter‑based instrumentation* +
 Implemented in: xref:../counter/index.adoc#purpose[`counter`]

* *Defining shared instrumentation interfaces* +
 Implemented in: xref:../interfaces/index.adoc#purpose[`interfaces`]

* *Activating the instrumentation system* +
 Implemented in: xref:../agent/index.adoc#purpose[`agent`]

* *Providing example usage* +
 Implemented in: xref:../example/index.adoc#purpose[`example`]