= example module

include::../-navigationForChildren.adoc[]

[#purpose]
== Purpose

The `example` module provides *demonstration code* that shows how the instrumentation system behaves in practice. +
Its responsibilities include:

* offering runnable examples for developers
* illustrating how counters and cost metrics appear in real code
* serving as a reference for testing and experimentation

In essence:

____

The `example` module demonstrates how the instrumentation framework works when applied to real Java classes.

____

'''

=== Out of Scope (Handled by Other Modules)

* *Implementing instrumentation logic* +
 Implemented in: xref:../counter/index.adoc#purpose[`counter`], xref:../metrics-cost/index.adoc#purpose[`metrics-cost`], xref:../metrics-cost-unnamed/index.adoc#purpose[`metrics-cost-unnamed`]

* *Collecting or aggregating measurement data* +
 Implemented in: xref:../collection/index.adoc#purpose[`collection`]

* *Defining shared instrumentation interfaces* +
 Implemented in: xref:../interfaces/index.adoc#purpose[`interfaces`]

* *Activating the instrumentation system* +
 Implemented in: xref:../agent/index.adoc#purpose[`agent`]