name: Publish Site to Pages (incl. Jacoco, JavaDoc)

on:
  push:
    branches:
      - master

permissions:
  contents: write
#  pages: write
#  id-token: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      #
      # Java
      #
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      #
      # Maven verify
      #
      - name: Build
        run: mvn -B clean verify

      # ==================================================
      # Copy module JavaDocs + Coverage
      # ==================================================
      - name: Collect reports
        run: |
          
          modules=(
            interfaces
            counter
            collection
            metrics-cost
            metrics-cost-unnamed
            agent
            example
          
            tests/empty
            tests/jar
            tests/jar-blocked
            tests/jar-module
            tests/integration
          )
          
          for module in "${modules[@]}"; do
          
            module_name=$(basename "$module")
          
            echo "Processing $module"
          
            # ------------------------------
            # JavaDoc
            # ------------------------------
          
            if [ -d "$module/target/reports/apidocs" ]; then
              mkdir -p "target/site/apidocs/$module_name"
          
              cp -r \
                "$module/target/reports/apidocs/"* \
                "target/site/apidocs/$module_name/"
            fi
          
            # ------------------------------
            # JaCoCo
            # ------------------------------
          
            if [ -d "$module/target/site/jacoco" ]; then
              mkdir -p "target/site/jacoco/$module_name"
          
              cp -r \
                "$module/target/site/jacoco/"* \
                "target/site/jacoco/$module_name/"
            fi
          
          done

      #
      # Maven version
      #
      - name: Extract Maven version
        run: |
          VERSION=$(mvn help:evaluate \
            -Dexpression=project.version \
            -q \
            -DforceStdout)

          echo "DOCS_VERSION=$VERSION" >> $GITHUB_ENV

      # ==================================================
      # Prepare versioned deployment
      # ==================================================
      - name: Prepare deployment structure
        run: |

          mkdir -p deploy/${DOCS_VERSION}
          mkdir -p deploy/latest

          rsync -av --exclude='*/.*' target/site/ deploy/${DOCS_VERSION}/
          rsync -av --exclude='*/.*' target/site/ deploy/latest/
      # cp -av target/site/ deploy/${DOCS_VERSION}/
      # cp -av target/site/ deploy/latest/

      # ==================================================
      # Deploy GitHub Pages
      # ==================================================
      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: deploy
          clean: false

      # ==================================================
      # Upload GitHub Pages artifact
      # ==================================================
      #- name: Upload Pages Artifact
      #  uses: actions/upload-pages-artifact@v3
      #  with:
      #    path: target/site

  #deploy:
  #  needs: build#

  #  runs-on: ubuntu-latest

  #  environment:
  #    name: github-pages
  #    url: ${{ steps.deployment.outputs.page_url }}

  #  steps:

      #- name: Deploy to GitHub Pages
      #  id: deployment
      #  uses: actions/deploy-pages@v4

